### ISSUE TITLE
[TASK] Consider min. required bond for pool creation

### ISSUE THREAD

**Issue by devpavan04** [tangle-network/dapp#2612]
### Overview

Users with zero balance should not be allowed to create liquid staking pools.

- [x] Fetch the min. bond required to create a LS pool
- [x] If the initial bond amount is less than the min. bond required, show an error

![CleanShot 2024-10-28 at 14 38 54](https://github.com/user-attachments/assets/5b3a99e8-c083-4b8f-925a-26be32f5baef)

https://github.com/user-attachments/assets/393042f9-ddca-48e5-8f3f-449e7542c583

**Comment by yurixander** [comment]
The bond amount required for creating pools can possibly be zero, depending on the network storage config, which is why I decided to skip the zero check, as it's not absolute. I believe this only applies to testnets or local net though.

![Screenshot 2024-10-29 at 16 02 17](https://github.com/user-attachments/assets/c0cdb5b5-2c9e-47cb-9c9e-d83d06fee438)

**Comment by devpavan04** [comment]
@yurixander, should we reopen this?

**Comment by yurixander** [comment]
> @yurixander, should we reopen this?

@devpavan04 Yes, I think what I'll do is first fetch and check the min. bond required for creating a pool. If the amount inputted is less than that, then show an input error.
